[package]
name = "shippi"
version = "0.1.0"
authors = ["Huy Tran <kingbazoka@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
